# Auto-generated by ggen rule `dspygen-architecture-catalog-python`.
# DO NOT EDIT. Edit `.specify/dspygen-architecture.ttl`, then run `ggen sync run`.

CAPABILITIES: tuple[dict[str, str], ...] = (
    {
        "id": "brce-intent",
        "label": "BRCE intent construction",
        "description": "Construct bounded effect intents addressed exclusively to BRCE; DSPyGen performs no direct actuation.",
        "lifecycle": "admitted",
        "standing": "ALIVE",
    },
    {
        "id": "evaluation-optimization",
        "label": "Evaluation and optimization",
        "description": "Evaluate DSPy programs against admitted datasets and bounded metrics before promotion.",
        "lifecycle": "qualified",
        "standing": "UNKNOWN",
    },
    {
        "id": "ggen-projection",
        "label": "ggen semantic projection",
        "description": "Project admitted RDF law into canonical Python and documentation surfaces without a generated directory.",
        "lifecycle": "admitted",
        "standing": "ALIVE",
    },
    {
        "id": "lsp-verification",
        "label": "LSP verification",
        "description": "Project admitted semantic constraints into diagnostics, navigation, and refactoring evidence.",
        "lifecycle": "active",
        "standing": "PARTIAL_ALIVE",
    },
    {
        "id": "mcp-boundary",
        "label": "MCP resource and tool boundary",
        "description": "Separate read-only resources from broker-addressed tools and preserve typed failures.",
        "lifecycle": "active",
        "standing": "PARTIAL_ALIVE",
    },
    {
        "id": "pipeline-composition",
        "label": "Pipeline composition",
        "description": "Compose dependency-closed DSPy programs with deterministic ordering and typed refusal.",
        "lifecycle": "admitted",
        "standing": "PARTIAL_ALIVE",
    },
    {
        "id": "receipt-replay",
        "label": "Receipt and replay",
        "description": "Bind source and projections with canonical BLAKE3 receipts that can be independently replayed.",
        "lifecycle": "admitted",
        "standing": "ALIVE",
    },
    {
        "id": "signature-manufacturing",
        "label": "Signature manufacturing",
        "description": "Manufacture typed DSPy signatures and modules from admitted semantic declarations.",
        "lifecycle": "admitted",
        "standing": "PARTIAL_ALIVE",
    },
)

CAPABILITY_BY_ID = {capability["id"]: capability for capability in CAPABILITIES}
