"""Independent read-only verifier for the ggen-managed architecture surfaces."""
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

from dspygen.architecture.model import EvidenceSet, Standing
from dspygen.architecture.receipt import verify_receipt

_SOURCE = ".specify/dspygen-architecture.ttl"
_OUTPUTS = (
    "src/dspygen/architecture/catalog.py",
    "docs/architecture/CATALOG.md",
)
_CAPABILITY_PATTERN = re.compile(
    r"dspygen:[A-Za-z0-9_]+\s+a\s+dspygen:Capability\s*;"
    r"\s*dspygen:capabilityId\s+\"(?P<id>[^\"]+)\"\s*;"
    r"\s*rdfs:label\s+\"(?P<label>[^\"]+)\"\s*;"
    r"\s*dcterms:description\s+\"(?P<description>[^\"]+)\"\s*;"
    r"\s*dspygen:lifecycle\s+\"(?P<lifecycle>[^\"]+)\"\s*;"
    r"\s*dspygen:standing\s+\"(?P<standing>[^\"]+)\"\s*;",
    re.MULTILINE,
)


@dataclass(frozen=True)
class VerificationReport:
    standing: Standing
    checks: dict[str, bool]
    failures: tuple[str, ...]
    receipt_root: str | None

    @property
    def ok(self) -> bool:
        return self.standing is Standing.ALIVE

    def to_dict(self) -> dict[str, object]:
        return {
            "schema": "dspygen.architecture.verifier-report.v1",
            "standing": self.standing.value,
            "checks": dict(sorted(self.checks.items())),
            "failures": list(self.failures),
            "receipt_root": self.receipt_root,
        }


def repository_root() -> Path:
    return Path(__file__).resolve().parents[3]


def _capabilities(source: str) -> list[dict[str, str]]:
    capabilities = [match.groupdict() for match in _CAPABILITY_PATTERN.finditer(source)]
    return sorted(capabilities, key=lambda capability: capability["id"])


def _render_python(capabilities: list[dict[str, str]]) -> bytes:
    lines = [
        "# Auto-generated by ggen rule `dspygen-architecture-catalog-python`.",
        "# DO NOT EDIT. Edit `.specify/dspygen-architecture.ttl`, then run `ggen sync run`.",
        "",
        "CAPABILITIES: tuple[dict[str, str], ...] = (",
    ]
    for capability in capabilities:
        lines.extend(
            [
                "    {",
                f'        "id": "{capability["id"]}",',
                f'        "label": "{capability["label"]}",',
                f'        "description": "{capability["description"]}",',
                f'        "lifecycle": "{capability["lifecycle"]}",',
                f'        "standing": "{capability["standing"]}",',
                "    },",
            ]
        )
    lines.extend(
        [
            ")",
            "",
            'CAPABILITY_BY_ID = {capability["id"]: capability for capability in CAPABILITIES}',
            "",
        ]
    )
    return "\n".join(lines).encode()


def _render_docs(capabilities: list[dict[str, str]]) -> bytes:
    lines = [
        "<!-- Auto-generated by ggen rule `dspygen-architecture-catalog-docs`. -->",
        "<!-- DO NOT EDIT. Edit `.specify/dspygen-architecture.ttl`, then run `ggen sync run`. -->",
        "",
        "# DSPyGen Architecture Catalog",
        "",
        "| Capability | Lifecycle | Standing | Contract |",
        "|---|---|---|---|",
    ]
    for capability in capabilities:
        lines.append(
            f'| `{capability["id"]}` | `{capability["lifecycle"]}` | '
            f'`{capability["standing"]}` | {capability["description"]} |'
        )
    lines.extend(
        [
            "",
            "`ALIVE` requires a positive witness, negative falsifier, independent verifier, receipt verifier, and replay. Lifecycle and standing are orthogonal. All effectful intents are addressed to `BRCE`.",
            "",
        ]
    )
    return "\n".join(lines).encode()


def verify(root: Path | None = None) -> VerificationReport:
    root = root or repository_root()
    checks: dict[str, bool] = {}
    failures: list[str] = []
    receipt_root: str | None = None

    source_path = root / _SOURCE
    checks["source_present"] = source_path.is_file()
    if not checks["source_present"]:
        return VerificationReport(Standing.BUILD_BROKEN, checks, ("SOURCE_MISSING",), None)

    source_bytes = source_path.read_bytes()
    source_text = source_bytes.decode()
    capabilities = _capabilities(source_text)
    checks["capabilities_admitted"] = len(capabilities) >= 8
    if not checks["capabilities_admitted"]:
        failures.append("CAPABILITY_ADMISSION_REFUSED")

    expected = {
        _OUTPUTS[0]: _render_python(capabilities),
        _OUTPUTS[1]: _render_docs(capabilities),
    }
    actual: dict[str, bytes] = {}
    for path, expected_bytes in expected.items():
        target = root / path
        present = target.is_file()
        checks[f"present:{path}"] = present
        if not present:
            failures.append(f"PROJECTION_MISSING:{path}")
            continue
        actual_bytes = target.read_bytes()
        actual[path] = actual_bytes
        matches = actual_bytes == expected_bytes
        checks[f"matches:{path}"] = matches
        if not matches:
            failures.append(f"ARTIFACT_DRIFT_REFUSED:{path}")

    checks["no_generated_tree"] = not (root / "generated").exists()
    if not checks["no_generated_tree"]:
        failures.append("GENERATED_TREE_REFUSED")

    model_source = (root / "src/dspygen/architecture/model.py").read_text()
    forbidden = ("subprocess", "socket", "requests", "urllib", "Command(", "os.system")
    checks["pure_kernel_boundary"] = not any(token in model_source for token in forbidden)
    if not checks["pure_kernel_boundary"]:
        failures.append("DIRECT_ACTUATION_IMPORT_REFUSED")

    receipt_path = root / "receipts/dspygen-architecture-v1.json"
    checks["receipt_present"] = receipt_path.is_file()
    receipt_ok = False
    if receipt_path.is_file() and len(actual) == len(_OUTPUTS):
        receipt = json.loads(receipt_path.read_text())
        receipt_ok, result = verify_receipt(receipt, source_bytes, actual)
        if receipt_ok:
            receipt_root = result
        else:
            failures.append(result)
        checks["receipt_verified"] = receipt_ok
        checks["receipt_evidence_complete"] = receipt.get("evidence") == {
            "falsifier": True,
            "independent_verifier": True,
            "receipt_verifier": True,
            "replay": True,
            "witness": True,
        }
        if not checks["receipt_evidence_complete"]:
            failures.append("EVIDENCE_INCOMPLETE")
    else:
        checks["receipt_verified"] = False
        checks["receipt_evidence_complete"] = False
        failures.append("RECEIPT_MISSING_OR_UNREPLAYABLE")

    evidence = EvidenceSet(
        witness=all(checks.get(f"matches:{path}", False) for path in _OUTPUTS),
        falsifier=checks["capabilities_admitted"],
        independent_verifier=checks["pure_kernel_boundary"],
        receipt_verifier=receipt_ok,
        replay=receipt_ok and not failures,
    )
    standing = evidence.standing() if not failures else Standing.BUILD_BROKEN
    return VerificationReport(standing, checks, tuple(failures), receipt_root)
