"""config — manage dspygen configuration via .dspygen.env."""
import os
import shutil
from pathlib import Path

import typer

app = typer.Typer(help="Manage dspygen configuration.")

ENV_FILE = Path(".dspygen.env")
ENV_EXAMPLE_FILE = Path(".env.example")

# Keys that dspygen cares about (for `show`)
DSPYGEN_KEYS = [
    "OPENAI_API_KEY",
    "GROQ_API_KEY",
    "OLLAMA_HOST",
    "DSPYGEN_MODEL",
    "DSPYGEN_MAX_TOKENS",
    "DSPYGEN_LOG_LEVEL",
]


def _mask_value(key: str, value: str) -> str:
    """Mask sensitive keys so values are never printed in full."""
    sensitive = {"OPENAI_API_KEY", "GROQ_API_KEY"}
    if key in sensitive and len(value) > 4:
        return value[:3] + "****"
    return value


def _read_env_file(path: Path) -> dict[str, str]:
    """Parse a simple KEY=VALUE env file, ignoring comments and blank lines."""
    result: dict[str, str] = {}
    if not path.exists():
        return result
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, _, val = line.partition("=")
            result[key.strip()] = val.strip()
    return result


def _write_env_file(path: Path, data: dict[str, str]) -> None:
    """Write KEY=VALUE pairs to an env file, preserving existing lines."""
    lines: list[str] = []
    if path.exists():
        raw = path.read_text().splitlines()
        handled: set[str] = set()
        for line in raw:
            stripped = line.strip()
            if stripped and not stripped.startswith("#") and "=" in stripped:
                k = stripped.partition("=")[0].strip()
                if k in data:
                    lines.append(f"{k}={data[k]}")
                    handled.add(k)
                    continue
            lines.append(line)
        for key, val in data.items():
            if key not in handled:
                lines.append(f"{key}={val}")
    else:
        for key, val in data.items():
            lines.append(f"{key}={val}")
    path.write_text("\n".join(lines) + "\n")


@app.command("show")
def config_show():
    """Print all dspygen-relevant env vars (sensitive values are masked)."""
    file_data = _read_env_file(ENV_FILE)
    typer.echo(f"\ndspygen config  (source: env + {ENV_FILE})\n" + "─" * 44)
    for key in DSPYGEN_KEYS:
        # Environment takes precedence over the file
        value = os.environ.get(key) or file_data.get(key)
        if value:
            display = _mask_value(key, value)
            source = "(env)" if os.environ.get(key) else f"({ENV_FILE})"
            typer.echo(f"  {key:<28} {display}  {typer.style(source, fg=typer.colors.BRIGHT_BLACK)}")
        else:
            typer.echo(
                f"  {key:<28} "
                + typer.style("not set", fg=typer.colors.YELLOW)
            )
    typer.echo("─" * 44)


@app.command("set")
def config_set(
    key: str = typer.Argument(..., help="Configuration key to set"),
    value: str = typer.Argument(..., help="Value to assign"),
):
    """Write KEY=VALUE to .dspygen.env in the current directory."""
    existing = _read_env_file(ENV_FILE)
    existing[key] = value
    _write_env_file(ENV_FILE, existing)
    typer.echo(
        typer.style("✓", fg=typer.colors.GREEN)
        + f"  {key} written to {ENV_FILE}"
    )


@app.command("get")
def config_get(
    key: str = typer.Argument(..., help="Configuration key to read"),
):
    """Read a value from .dspygen.env or the environment."""
    value = os.environ.get(key)
    source = "env"
    if value is None:
        file_data = _read_env_file(ENV_FILE)
        value = file_data.get(key)
        source = str(ENV_FILE)
    if value is None:
        typer.echo(typer.style(f"{key} is not set", fg=typer.colors.YELLOW))
        raise typer.Exit(code=1)
    display = _mask_value(key, value)
    typer.echo(f"{display}  " + typer.style(f"({source})", fg=typer.colors.BRIGHT_BLACK))


@app.command("init")
def config_init(
    force: bool = typer.Option(False, "--force", "-f", help="Overwrite existing .dspygen.env"),
):
    """Create .dspygen.env from .env.example (or a built-in template)."""
    if ENV_FILE.exists() and not force:
        typer.echo(
            typer.style("!", fg=typer.colors.YELLOW)
            + f"  {ENV_FILE} already exists. Use --force to overwrite."
        )
        raise typer.Exit(code=1)

    if ENV_EXAMPLE_FILE.exists():
        shutil.copy(ENV_EXAMPLE_FILE, ENV_FILE)
        typer.echo(
            typer.style("✓", fg=typer.colors.GREEN)
            + f"  Created {ENV_FILE} from {ENV_EXAMPLE_FILE}"
        )
    else:
        # Write a sensible built-in template
        template_lines = [
            "# dspygen configuration — generated by `dspygen config init`",
            "# Copy this file to .dspygen.env and fill in your values.",
            "",
            "OPENAI_API_KEY=",
            "GROQ_API_KEY=",
            "OLLAMA_HOST=http://localhost:11434",
            "DSPYGEN_MODEL=",
            "DSPYGEN_MAX_TOKENS=",
            "DSPYGEN_LOG_LEVEL=INFO",
        ]
        ENV_FILE.write_text("\n".join(template_lines) + "\n")
        typer.echo(
            typer.style("✓", fg=typer.colors.GREEN)
            + f"  Created {ENV_FILE} from built-in template"
        )
        typer.echo(f"  Edit {ENV_FILE} to add your keys.")


def main():
    app()


if __name__ == "__main__":
    main()
